module.exports = {
  "ALIVE_IMG": "https://raw.githubusercontent.com/RASH-DATA/ANJU-DATA/refs/heads/main/WhatsApp%20Image%202024-09-08%20at%209.00.17%20PM.jpeg",
  "PREFIX": ".",
  "AUTO_READ_STATUS": true,
  "MODE": "private",
  "BOT_NUMBER": "94784924900",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": true,
  "AUTO_VOICE": true,
  "AUTO_STICKER": true,
  "AUTO_REPLY": true,
  "AUTO_REACT": false,
  "WELCOME": true,
  "ANTI_BAD": false,
  "ANTI_BOT": false,
  "ANTI_LINK": false,
  "ANTI_CALL": true,
  "ANTI_DELETE": true,
  "ALLWAYS_ONLINE": true,
  "MOROCCO_BLOCK": true,
  "BTN_MSG": false,
  "OWNER_NAME": "@Ima_Xz",
  "NEWS_JID": "1234567890@s.whatsapp.net",
  "MOVIE_JID": false,
  "ANIME_JID": false,
  "AUTO_TYPING": true,
  "AUTO_RECORDING": true,
  "AUTO_NEWS": false,
  "OWNER_REACT": true,
  "EMOJI": "👾",
  "AI_MODE": false,
  "BANNED": [],
  "SUDO": [
    "94784924900"
  ]
};
